### ISSUE TITLE
Empty argument strings are not visible in the HTML report

### ISSUE THREAD

**Issue by janschaefer** [TNG/JGiven#11]
### Current Behavior
```
Given a scenario
  and the scenario has one step with an empty string as argument
when creating the HTML report
  then the empty string is not visible in the report
```
### Expected Behavior
```
Given a scenario
  and the scenario has one step with an empty string as argument
when creating the HTML report
  then the empty string is displayed as '<empty>' in a gray color
```

**Comment by Airblader** [comment]
Did formatter annotations exist back when this issue was raised? IMHO, the best solution here would be if the test simply used `@Quoted`, which would fix this issue for *all* report generators.

That said, if we still want to fix this in the HTML generator (and possibly others), one proposal would be the em-dash "—". Another option, which *only* works for HTML, would be to visually indicate it:

> then the empty string is displayed as ` `.

Although I don't quite favor this because it's a rather inconsistent representation. The HTML report could also just visually accent *all* arguments, then this issue would disappear entirely (for HTML).

Personally I prefer a solution that works in all reporters and there's a couple more details we'd have to discuss for such a solution. First I think we should clarify whether we shouldn't just expect users who allow empty string arguments to use an appropriate formatter annotation.

**Comment by Airblader** [comment]
Actually I think displaying *anything* for an empty string could break test reports for users. For example in a scenario like this:

````
public SELF some_process_has_$_run( @YesNo( yes = "", no = "not" ) boolean hasRun ) { … }
```

(some obvious pseudo-code)

**Comment by janschaefer** [comment]
Well, maybe we should close this issue
