### ISSUE TITLE
Report is messed up when method used in SimpleScenarioTest is private

### ISSUE THREAD

**Issue by nikowitt** [TNG/JGiven#110]
Hi,
when using a SimpleScenarioTest, all methods I implement must not be private, otherwise the report gets messed up:

```
package com.sobis.suma.tests;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.test.context.ContextConfiguration;

import com.sobis.jaf.JAFConstants;
import com.sobis.jaf.tests.spring.ApplicationJUnit4ClassRunner;
import com.sobis.jaf.tools.JAFLogger;
import com.sobis.suma.tests.PrivateTest.PrivateStage;
import com.tngtech.jgiven.Stage;
import com.tngtech.jgiven.junit.SimpleScenarioTest;

@RunWith(ApplicationJUnit4ClassRunner.class)
@ContextConfiguration(locations = { JAFConstants.APPLICATION_CONTEXT })
public class PrivateTest extends SimpleScenarioTest<PrivateStage> {
	public static final JAFLogger LOGGER = new JAFLogger(PrivateTest.class);

	@Test
	public void test_report() {
		given().something();
		when().something_is_done();
		then().something_is_expected();
	}

	static class PrivateStage extends Stage<PrivateStage> {

		public PrivateStage something_is_done() {
			return self();

		}

		public PrivateStage something_is_expected() {
			return self();

		}

		public PrivateStage something() {
			return self();

		}

	}
}
```
results in

Test Class: com.sobis.suma.tests.PrivateTest

 Scenario: test report

   Given something
    When something is done
    Then something is expected

Using the private modifier somewhere, e.g.
```
package com.sobis.suma.tests;

import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.test.context.ContextConfiguration;

import com.sobis.jaf.JAFConstants;
import com.sobis.jaf.tests.spring.ApplicationJUnit4ClassRunner;
import com.sobis.jaf.tools.JAFLogger;
import com.sobis.suma.tests.PrivateTest.PrivateStage;
import com.tngtech.jgiven.Stage;
import com.tngtech.jgiven.junit.SimpleScenarioTest;

@RunWith(ApplicationJUnit4ClassRunner.class)
@ContextConfiguration(locations = { JAFConstants.APPLICATION_CONTEXT })
public class PrivateTest extends SimpleScenarioTest<PrivateStage> {
	public static final JAFLogger LOGGER = new JAFLogger(PrivateTest.class);

	@Test
	public void test_report() {
		given().something();
		when().something_is_done();
		then().something_is_expected();
	}

	static class PrivateStage extends Stage<PrivateStage> {

		PrivateStage something_is_done() {
			return self();

		}

		private PrivateStage something_is_expected() {
			return self();

		}

		PrivateStage something() {
			return self();

		}

	}
}
```
creates
Test Class: com.sobis.suma.tests.PrivateTest

 Scenario: test report

   Given something
    When something is done
    Then self

The last method line is used in the report in this case.

I think it makes sense to automatically throw an exception when a private method is encountered, doesn't it?

Best regards,
Niko

**Comment by janschaefer** [comment]
Yes, this shouldn't be the case. I will have a look at that.

**Comment by janschaefer** [comment]
This issue is not fixable. The problem is that JGiven uses cglib proxies to intercept the methods. Private methods, however, cannot be intercepted, so JGiven can neither put them into the report nor throw exceptions. I fear the only thing I can do about this is to document it. I have extended the documentation accordingly: http://jgiven.org/docs/stages/

**Comment by nikowitt** [comment]
Just my 2 cents regarding this issue without any additional knowledge: isn't it possible to indirectly check the result by comparing a report string against the original  test method which is the entry point of the whole trace instead of trying to check the modifiers?

In my case, the self in "then" does not match the method "something_is_expected".

There might be cases when the report is modified with annotations like @As, but maybe this is a help for the majority of cases. But maybe this is too complicated :)

**Comment by janschaefer** [comment]
Technically JGiven captures the method calls at runtime using a proxy mechanism. In particular, JGiven does not parse the source code. The problem is that it is technically not possible to intercept private methods in Java using a proxy. So JGiven can never find out that the method `something_is_expected` was ever called. Sure it would be somehow possible to parse the source code of the test method to check that. But this has other drawbacks and in addition would be very complex. I also think that it is a very rare usecase to use private methods in scenarios. Typically you want to share stages between scenarios and test classes, in which case the step methods cannot be private.

**Comment by nikowitt** [comment]
Yes, you are right - the original idea is to give developers a hint what they have done wrong when the result doesn't match the expectation. But I totally agree to the fact that the effort exceeds the benefit.

Thanks for your feedback!
