### ISSUE TITLE
Allow @Format for @Test method parameter

### ISSUE THREAD

**Issue by nikowitt** [TNG/JGiven#114]
It's me again :)

```
   public void check_last_award_date(DateTime expectedDate,
                                      Integer quotationPositionToRemoveAwardDateFrom,
                                      DateTime... providedDates)   throws Exception {
```

creates a report like
```
 Case 1: expectedDate = 2015-01-01T00:00:00.000+01:00,
quotationPositionToRemoveAwardDateFrom = null, providedDates =
2015-01-01T00:00:00.000+01:00
```

Even when I supply a @Formatter to the variables, the report still looks the same. Appearantly, @Formatters are only evaluated inside the test class, but not on the test class itself.

Best regards,
Niko

**Comment by janschaefer** [comment]
Well, I have expected that, after I saw your report ;-)

Currently, the formatters are only used for step methods. The problem is a bit, that the parameter values only appear if you have multiple cases, but no data table. However, I think this feature is quite useful and should also not be too difficult to implement.

**Comment by janschaefer** [comment]
It was nearly trivial to implement ;-)

**Comment by nikowitt** [comment]
Nice to hear :)
