### ISSUE TITLE
Show final methods in test report

### ISSUE THREAD

**Issue by mmonetha-sobis** [TNG/JGiven#1162]
Hi, at my company...

... in our codebase there are several overloaded step methods. We want to mark some of those methods that shouldn't be overriden as final. Here's an example

**Method 1** (non-final, overloading Method 2, used as step method, should be overridden)
```
public T user_creates(Class<?> clazz, boolean visible, ValuePair... values) {
	user_creates(clazz, values);
	setDefaultValues(visible);
	return self();
}
```
**Method 2** (final, overloading Method 3, shouldn't be overridden, but should be used directly as step method)
```
public final T user_creates(Class<?> clazz, ValuePair... values) {
	return user_creates(clazz, createRequestParamsForClass(clazz, values));
}
```
**Method 3** (final, shouldn't be overridden)
```
public final T user_creates(Class<?> clazz, RequestParams params) {
	//do complex stuff 
	return self()
}
```
... the final methods are sometimes also used directly as step method and hence should be shown in the test report.

The current behaviour when we directly use a final step method is that, the method is executed but not shown in the test report (as stated in the JGiven User Guide - 5.1 Step Methods, this is expected behavior)

Is there any possible workaround for this?

**Comment by l-1squared** [comment]
Dear @mmonetha-sobis,

we're using byte-buddy to subclass and intercept the stage, and we're doing this dynamically. Since the JVM is really strict when it comes to handling `final` members, there is no way of dynamically altering them.

So, from the top of my  head, what I think is happening here is that byte buddy just fails to override this method, therfore, instead of the method that will record this step in JGiven, the original one is called. 

Unfortunately, ByteBuddy lies pretty much at the core of JGiven, and I do not see a simple way around this issue that would let you keep your methods final. 
I do however have some ideas that could help you achieve both goals, each of course with drawbacks:
* You could use a static code analysis tool, like ArchUnit to ensure that a method is not overridden.
* Depending on how your code is structured you could play around with the visibility modifier and use `package-private` instead of public.

**Comment by l-1squared** [comment]
Closed, question is hopefully answered

**Comment by mmonetha-sobis** [comment]
Hi, thanks for your quick answer. Since there is no easy solution for this, closing the issue is fine for me.
