### ISSUE TITLE
Add a StageScope similar to ScenarioScope from cucumber-spring

### ISSUE THREAD

**Issue by ecattez** [TNG/JGiven#1384]
As I come from Cucumber with Spring context, I think that it would be nice to define beans with a `StageScope`, similar to cucumber-spring `ScenarioScope`. This way, it will be easy to let Spring refresh beans between each stage.

```
@EnableJGiven
@TestConfiguration
public class SomeTestModule {

    @Bean
    @StageScope
    StageContext context() {
        return new StageContext(); // should be refreshed between each stage
    }

    @Bean
    @StageScope
    SomeSPI someSPI() {
        return mock(SomeSPI.class); // mock should be reset between each stage
    }
```

What do you think about it ?

**Comment by l-1squared** [comment]
Hi, sorry for answering late, I've been a bit busy this week.

Before I going to state my opinion on the matter, I'd like to ask a few questions back, So for instance, what should the exact scope of these stage classes be?  My quick glance at cucumber's scenario stage suggested to me that the module would be exchanged after a scenario, whereas to me, a stage scope suggests that the dependency is supposed to be exchanged within a single scenario, however nonsensical that may be.

A further complication ensues from the way you presented your suggestion. For this to work JGiven would have to somehow intercept the spring Bean definition setup process (I guess) which is something JGiven is really not equipped to do, and also, at least from the last time I tried, is something spring really doesn't want you to do. 

Finally, for the actual use case you present, there might be a variety of solutions that would work without a new annotation. 
For instance, you could use `@AfterStage` (or @AfterScenario if that's what you want) to reset the mocks manually. Or, if that is more to your liking, you could instruct spring to hand out a different instance of your mocks to each of your stage. This might be achieved by using springs "template" scope (at least I think thats what its called) or by wiring a provider of SPI (`()->mock(SomeSPI.class)`) instead of the SPI ittself.

Hope this helps,
best, 
l-1squared

**Comment by ecattez** [comment]
Hi, I think I confused between stage and scenario. I would like the beans to be refreshed between each _test_ and each instance of a parameterized test. So `@AfterScenario` is the correct annotation. It seems that the annotation can only be used in a stage instance (annotated by `@JGivenStage` in my case). However, a dependency, such as an SPI, can exist accross multiple stage classes. I would like to find a solution to refresh the SPI after any scenario.

For the mock example, in cucumber, I'm not using any scope but a MockRegistry like below, because mocks seems not to be reseted correctly between each scenario:

```
public class MockRegistry {

    private final List<Object> mockedClasses = new ArrayList<>();

    public <T> T mock(final Class<T> classToMock) {
        T mockedClass = Mockito.mock(classToMock);
        mockedClasses.add(mockedClass);
        return mockedClass;
    }

    public <T> T spy(final T classToSpy) {
        T spiedClass = Mockito.spy(classToSpy);
        mockedClasses.add(spiedClass);
        return spiedClass;
    }

    public void clearAllMocks() {
        mockedClasses.forEach(Mockito::reset);
    }

    public static class AfterScenarioHook {
        @Autowired
        private MockRegistry mockRegistry;

        @After // cucumber annotation
        public void tearDown() {
            mockRegistry.clearAllMocks();
        }
    }

}
```

I will try to use a provider as you suggest.

In my example, I'm also introducing a bean for a ScenarioContext (StageContext was not the right name). But I guess that I could use a jgiven annotation 🤔 Is it possible to combine `@JGivenStage` on the class with `@ScenarioState` on a field ?

**Comment by l-1squared** [comment]
JGivenStage and ScenarioState should work independently. 

Note also, that depending on the test framework you are using, you will get a new instance for each test that runs (its the default for JUnit). With the right bean scope you should get a new instance of your mock for every test
Finally springs @MockBean might also be worth a look for you

**Comment by ecattez** [comment]
I got some constraints that does not allow me to use `@MockBean` :/ I'm making spring autoconfigurations to use the ability to create beans based on `@ConditionalOnMissingBean`. This way, when I'm running tests, mocks and other fake implementations are in the bean registry and the autoconfiguration just skip the production implementations, as it is triggered after test configuration. `@MockBean` is going after autoconfiguration, so `@ConditionalOnMissingBean` is triggered and instances of product implementations are created.

**Comment by ecattez** [comment]
I agree. If you want, I can share you the link to the project to see how I handle everything with Spring and JGiven. The project will serve as an advanced example (next step will be to have JGiven report as github pages).

**Comment by l-1squared** [comment]
I'd be happy to have that

**Comment by l-1squared** [comment]
Closed, because viable alternatives eksist and the suggestion is hard to implement
