### ISSUE TITLE
Spring @JGivenStage has unexpected side effects

### ISSUE THREAD

**Issue by bodote** [TNG/JGiven#1567]
I've just started to use JGiven in a project, that already had a `@SpringBootTest`. However unfortunately now the old SpringBootTest also scans and includes my new `@JGivenStage`  class, but it shouldn't. Because I have one specific class `MyService` defined as a `@MockBean` in this `@JGivenStage`  class , but the old SpringBootTest actually needs to use the a **real object** of this `MyService` class, just as it did before I introduced JGiven.

Therefore the old SpringBootTest now uses the `@MockBean`  `MyService` from the JGiven Stage class  instead the real one and fails. 

The workaround I found is : 

I annotate my new JGiven - Test (which is a `@WebMvcTest` )  with `@ActiveProfile("jgiven")` and the  `@JGivenStage`  class with `@Profile("jgiven") so that it is ignored by the old SpringBootTest (and all other tests) but used by the new JGiven - Test.

The actual Problem seems  that all  `@JGivenStage` annotated test classes are used just like any other spring bean i.e. are used from all `@SpringBootTest` classes , which is not good (unless the workaround is applied).

Any Ideas how to handle this problem properly ?

**Comment by l-1squared** [comment]
Hi,
to me this seems like a problem that needs to be solved with Spring's toolset. Our spring integration is pretty straightforward and I fear that any more sophistication would produce a ton of edge cases and inconsistencies that would break either existing integrations or just simply be hard to understand as a user.

From the top of my head, solutions that I can think of couldl be: Disabling component scans in the test folder and construct the context for JGiven tests separately, or maybe declaring the mock bean in the test class instead of the Stage. Spring usually handles those rather well. Also, I think Spring 6 has something like "hierarchical contexts" but I have not worked with those yet.

**Comment by l-1squared** [comment]
will close this on Monday if there are no further comments.

**Comment by bodote** [comment]
The solution I found is:
don't put any `@MockBeans MyClass myObject`  in a @JGivenStage  - class , instead put it in the `@WebMvcTest` or the `@SpringBootTest` class and for the @JGivenStage  - class just use `@Autowire MyClass myObject` , that way I got my example to work.
