### ISSUE TITLE
Adding tags dynamically

### ISSUE THREAD

**Issue by janschaefer** [TNG/JGiven#172]
It might sometimes be useful to add tags dynamically to scenarios

**Comment by Airblader** [comment]
What should this look like from a design point of view? Do you want a method which takes a `TagConfiguration`?

**Comment by janschaefer** [comment]
I haven't really thought about that. I am not sure whether TagConfiguration is the right thing to use here. The TagConfiguration class is actually used to configure a tag. For applying a tag there should be a more narrow interface. In fact, it should only take the class of the annotation and and optional value, IMO.

**Comment by Airblader** [comment]
This could be more challenging than I originally anticipated. We need an actual instance of the annotation, not just its class, because we need to pass some instance to the DescriptionGenerator and HrefGenerator if they are being used.

However, creating a proper instance of an annotation isn't exactly easy. For example, Hibernate has [this proxy class](https://github.com/hibernate/hibernate-validator/blob/master/engine/src/main/java/org/hibernate/validator/internal/util/annotationfactory/AnnotationProxy.java) for that problem.

Of course, we could just either pass `null` for the annotation and document this, or disallow tag annotations which use a description or href generator.

**Comment by Airblader** [comment]
On a side note, could it be that there's a bug in `ScenarioModelBuilder#toTags`? The method exits early if `ignoreValue` is set. Both nested tags and the href attribute won't be set in this case, neither of which sounds right to me. Bug?
