### ISSUE TITLE
Formatters in abstract methods don't work properly

### ISSUE THREAD

**Issue by nikowitt** [TNG/JGiven#193]
Hi Jan,

```
public abstract class SupplierAndSupplierContactScenarioTest<SELF extends SupplierAndContactSecurityTestSteps<?, ENTITY>, ENTITY extends Base<?>> extends
        JAFSimpleScenarioTest<SELF> {
```

contains a test

```
    @Test
    @DataProvider({
            TRUE,
            FALSE
    })
    public void validate_read_access_for_supplier_contact(boolean isSupplierContact)
            throws Exception {
        given().entity_that_$_related_to_supplier_contact(isSupplierContact)
(...)

    }
```

with

```
public abstract SELF entity_that_$_related_to_supplier_contact(@IsIsNot boolean isSupplierContactRelated) throws Exception;
```

The implementing class is

```
public class SupplierSecurityTest extends SupplierAndSupplierContactScenarioTest<SupplierSecurityTestSteps, Supplier> {
```

and overrides

```
public SupplierSecurityTestSteps entity_that_$_related_to_supplier_contact(@IsIsNot boolean isSupplierContactRelated)
                throws Exception {
(...) }
```

Now the report does not consider the @IsIsNot formatter as it displays:

```
Given entity that true related to supplier contact
```

but I'm expecting

```
Given entity that is not related to supplier contact
```

or

```
Given entity that is related to supplier contact
```

So it seems that there is an issue with abstract methods somewhere.

Best regards,
Niko

**Comment by janschaefer** [comment]
Strange. I will have a look.

**Comment by janschaefer** [comment]
Which Java version are you using? I could reproduce the problem with Java 6 and Java 7. With Java 8 the problem is gone. I think the problem is related to #62. The reason is that Java generates so called _bridge_ methods in certain cases. For example, if you override a method using a different return type. The problem is now that the generated bridge method does not take over the annotations that have been applied to the original methods. This was fixed with Java 8 (see https://bugs.openjdk.java.net/browse/JDK-6695379). There are also ways to find the original method from the bridge method and take the annotations from there, however, this is quite complex, because you have to take overloading of methods into account. Spring provides a [BridgeMethodResolver](https://github.com/spring-projects/spring-framework/blob/master/spring-core/src/main/java/org/springframework/core/BridgeMethodResolver.java) for that, however, I do not want to introduce a dependency to Spring.

**Comment by nikowitt** [comment]
I think in this particular case I was using Java 7, so this makes perfectly sense. I will verify this as soon as possible.

**Comment by janschaefer** [comment]
any updates on this issue?

**Comment by nikowitt** [comment]
I'm currently on vacation, will check this next week in the office.

**Comment by janschaefer** [comment]
Ok, no problem. I would close this for now as a duplicate of #63. If it turns out to be a different issue then just reopen it.

**Comment by nikowitt** [comment]
Problem still exists with Java 1.8.0_72, so it seems that this is something different.

**Comment by janschaefer** [comment]
Maybe you need special rights :-). I reopened it.

**Comment by janschaefer** [comment]
I think this is really a duplicate of #247 right? I will close this then. If you think this is not the case, feel free to reopen it.
