### ISSUE TITLE
Execute tests based on tag

### ISSUE THREAD

**Issue by ratulmukh** [TNG/JGiven#218]
Is there a way to only execute tests that are specified with a certain tag? Something like JUnit categories? I would really like to just mention a tag in the maven command, and have only those tests with the given tag executed.

**Comment by janschaefer** [comment]
There is no direct way of doing this, because JGiven is relying on JUnit to execute the tests. As JGiven is implemented by JUnit rules and not as a Runner, JGiven can also not influence the execution of tests. However, what you could do is to turn JUnit categories into JGiven tags. To do so you have to use the `@JGivenConfiguration` tag at your test class (or a common super class of all your tests). With the tag you can provide a subclass of `AbstractJGivenConfiguration` where you can call the `configureTag` method to configure arbitrary Annotations to be JGiven tags.
