### ISSUE TITLE
Provide an example on how to use Mockito/JGiven for testing

### ISSUE THREAD

**Issue by ahus1** [TNG/JGiven#331]
Hi,

I built a example on how to test Spring application with JGiven and Mockito. The example turned out a little bigger than thought initially. 

See this class as a start: [GivenCalculatorDomainStage.java](https://github.com/ahus1/bdd-examples/blob/master/jgiven-mockito-spring/src/test/java/de/ahus1/bdd/calculator/domainstyle/bdd/GivenCalculatorDomainStage.java) and the [README.adoc](https://github.com/ahus1/bdd-examples/tree/master/jgiven-mockito-spring) for more information about the DDD/Hexagonal ideas.

The idea is to provide the right mix of Mock/Spy/InjectMocks/ProvidedScenarioState/BeforeScenario annotations together with MockitoAnnotations.initMocks.

The result will be a fast running test as no Spring context needs to be initialized.

I look forward to more comments and ideas on how to provide a smaller example. I'm then happy to provide a PR to either enhance the Spring example or provide a new example.

**Comment by janschaefer** [comment]
Hi :-)

great that you are working on JGiven examples! In this concrete case, however, I would actually not use Mockito at all, because you can easily implement the in-memory implementation of the repository without the use of Mockito. This makes the test code easier to understand (IMHO) and also provides a solution that is easily usable in other tests as well. I quickly implemented that: https://github.com/janschaefer/bdd-examples/commit/c68b3c711671a10e2781ee37db39babcb91637a3.

**Comment by ahus1** [comment]
Right, this example still very easy - and when you have injection via the constructor there is one reason less to use Mockito at all. 

I merged part of your commit - it's now using the in memory repository as a java class, but still shows the use of Mockito annotations. I'll wait and see how a better example with Mockito could look like. 

Thank you for your feedback! For now, I close this task.

**Comment by janschaefer** [comment]
Yes, sure, this is always the problem with simple examples, they are often a bit artificial. Hard to come up with a simple example that really requires Mockito :-)
