### ISSUE TITLE
using @Hidden on first statement breaks rendering of given when then.

### ISSUE THREAD

**Issue by jangalinski** [TNG/JGiven#356]
I have a scenario:

```
given()
     .some_technical_preparation()
    .and()
    .the_application_starts();
``` 

where "some_technical_preparation" is annotated with @Hidden

I would expect the report:

          Given the application starts

but instead I get

         And the application starts

I cannot use @BeforeScenario in this case, because my tests requires another rule and it is not yet initialized in the @BeforeScenario method.

**Comment by janschaefer** [comment]
While first I thought this is a bug, it is in fact expected behavior. You can easily workaround that issue, by just not having an `.and()` after the hidden step. In fact I recommend to have hidden steps in camelCase to make immediately clear in the scenario that the step will not be visible. Your scenario should look as follows:

```
given().someTechnicalPreparation()
    .the_application_starts();
```
