### ISSUE TITLE
question - call test as a step

### ISSUE THREAD

**Issue by nnar1o** [TNG/JGiven#375]
I need to test a webservice. I try to find a clean solution how to create tests.
First test I wrote is:
```
class LoginTest ... {
@Test public void user_should_be_logged_in(){
 given().login_credentials(); 
 when().login_request_is_sent();
 then().user_is_logged().and().session_token_is_obtained();
}
}
```
is it possible to use this test as a "given" condition in a different test class?
i.e.:
```
class EnrollTest ... {

@Test public void should_modify_item(){
   given().logged_user(); // here I want to be called LoginTest.user_should_be_logged_in(). And session token needs to be returned.
when().item_is_modified(); // here I need to use the token form login method
} 

}
```

Do you have any suggestions how to write it? Generally I want to use a result of one test scenario as a given condition in a different test. should I use this http://jgiven.org/userguide/#_subclassing_of_stages? 

I use JUnit 4.

Sorry if it is a wrong place to ask such questions.

**Comment by codecholeric** [comment]
My 2 cents are, that I never did really well with inheritance for stages. So what we switched to is having many composable stages, i.e. several given, when and then stages according to domain context.
For your case I'd try to reuse those stages within your other stage, e.g.

```
public class EnrollGiven {
    LoginGiven loginGiven = ...; // inject it?
    LoginWhen loginWhen = ...; // inject it?

    EnrollGiven a_logged_in_user() {
        loginGiven.login_credentials(); 
        loginWhen.login_request_is_sent();
    }
}
```

Or have some test utility component that can create credentials and perform a login and just delegate to that component from your `LoginStage` as well as your `EnrollStage`.

In my project we pretty much dropped all super classes and wrote a little bit of injection glue code to write something like

```
@Given
UserGiven givenUser;
@Given
ProductGiven givenProduct;
@When
ImportWhen whenImport;
// ...
```

And these stages we compose according to the current domain context to test. Works pretty well and makes refactoring way more easy due to less coupling than by inheritance (which really bit me in the a** from time to time).

**Comment by codecholeric** [comment]
I know it's not exactly your question, but I wanted to add that JGiven already supports this stage injection out of the box with JUnit support, so what I would recommend instead of inheritance is something like

```
public class SomeTest {

    @ClassRule
    public static final JGivenClassRule writerRule = new JGivenClassRule();

    @Rule
    public final JGivenMethodRule scenarioRule = new JGivenMethodRule();

    @ScenarioStage
    FooGiven fooGiven;
    @ScenarioStage
    BarGiven barGiven;
    @ScenarioStage
    FooWhen fooWhen;
    @ScenarioStage
    BarWhen barWhen;
    @ScenarioStage
    FooThen fooThen;
    @ScenarioStage
    BarThen barThen;

    @Test
    public void some_scenario() {
        fooGiven.some_foo();
        barGiven.some_bar();

        fooWhen.some_foo();
        barWhen.some_bar();

        fooThen.some_foo();
        barThen.some_bar();
    }
}
```

(compare http://jgiven.org/userguide/#_using_junit_rules_directly_instead_of_deriving_from_scenariotest)
