### ISSUE TITLE
stage subclass - intro words

### ISSUE THREAD

**Issue by nnar1o** [TNG/JGiven#404]
I tried to use your stage subclasses example code, but it does not compile (https://github.com/TNG/JGiven/tree/master/jgiven-examples/src/test/java/com/tngtech/jgiven/examples/subclassing):

```
public class CommonStagesTest extends SimpleScenarioTest<GivenSpecialStepsFixed> {

    // tag::onlyMethod[]
    @Test
    public void subclassing_of_stages_should_work() {
        given().my_common_step()
          .and().cant_do_this(); <-- compilation error after .and().
    }
  //end::onlyMethod[]
}
```

**Comment by nnar1o** [comment]
Or could someone provide a working scenario with use a common stage class as a base for other stages  - I want to refactor my code and common base stages would help me organize my tests code.

**Comment by codecholeric** [comment]
Hey, I think you have a copy & paste error there, it should be

```
public class CommonStagesTest extends SimpleScenarioTest<GivenSpecialSteps> { ... }
```

If you extend from `SimpleScenarioTest<GivenSpecialStepsFixed>` but omit the `SELF` type parameter of `GivenSpecialStepsFixed`, the Java compiler will lose all type info and not know your stage type anymore within the fluent API.

**Comment by codecholeric** [comment]
That being said, I would advise against using inheritance too much to organize your stages. At most one level. At least from my experience otherwise at some point it will be a maintenance hell.
I've had a better experience to cut the domain into small pieces and provide a custom stage for each domain part, then use more than 3 stages (i.e. `UserGiven`, `TenantGiven`, `OrderGiven`, `CatalogGiven`, and so on)
